### ISSUE TITLE
dython correlation_ration error

### ISSUE THREAD

**Issue by syometche** [shakedzy/shakedzy#1]
Hi  shakedzy and the community,

the dataset is an E-commerce data from Olist store. There are 9 dataset. After cleaning and mapping the data, I want to make the correlation between the variable. The variable type are numerical and categrorical, date.  I use the dython package to have the correlation beetween variable, but it didn't work. 

For the categorical varibale there are: 
seller_city = 604 unique value
customer_city = 4033 unique value
product_category = 21 unique value
seller_state = 23 unique value
customer_state = 27 unique value
payment_type = 2 unique value
order_status = 2 unique value

other variable are numeric or date. 

kaggle: https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce. 

My code :
from dython.nominal import associations

Thank to help me

![image](https://user-images.githubusercontent.com/82031522/234486186-34f92cc8-4f98-40e8-94f2-d96e104610ee.png)
![image](https://user-images.githubusercontent.com/82031522/234486337-8ddad9c2-e9d2-4eba-bc28-5f8715d91280.png)

**Comment by shakedzy** [comment]
Hey @syometche - this is not the dython repo. Please open you ticket [here](https://github.com/shakedzy/dython/issues), and make sure to add the clean data you used with the function.
